export const api = [
    {
        id: 1,
        type: 'select',
        title: 'Вид',
        values: ['обычный', 'необычный'],
    },
    {
        id: 2,
        type: 'select',
        title: 'Бренд',
        values: ['Бренд 1', 'Бренд 2'],
    },
    {
        id: 3,
        type: 'select',
        title: 'Подвид',
        values: ['Подвид 1', 'Подвид 2'],
    },
    {
        id: 4,
        type: 'select',
        title: 'Тип',
        values: ['Тип 1', 'Тип 2'],
    },
    {
        id: 5,
        type: 'select',
        title: 'Акция',
        values: ['Акция 1', 'Акция 2'],
    },
    {
        id: 6,
        type: 'numbers',
        title: 'Диаметр',
        min: 1,
        max: 100,
    },
    {
        id: 7,
        type: 'numbers',
        title: 'Объем, л',
        min: 1,
        max: 100,
    },
    {
        id: 8,
        type: 'numbers',
        title: 'Рабочая температура, °С',
        min: 1,
        max: 100,
    },
    {
        id: 9,
        type: 'numbers',
        title: 'Длина, мм',
        min: 1,
        max: 100,
    },
    {
        id: 10,
        type: 'numbers',
        title: 'Ширина, мм',
        min: 1,
        max: 100,
    },
    {
        id: 11,
        type: 'numbers',
        title: 'Высота, мм',
        min: 1,
        max: 100,
    },
    {
        id: 12,
        type: 'numbers',
        title: 'Глубина, мм',
        min: 1,
        max: 100,
    },
]
